# Generated by Django 5.2 on 2025-07-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_userpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
