# Generated by Django 5.2 on 2025-06-21 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'اینستاگرام'), ('telegram', 'تلگرام'), ('whatsapp', 'واتساپ'), ('youtube', 'یوتیوب'), ('other', 'سایر')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('link', models.URLField()),
            ],
        ),
    ]
